name = "FerriteMultigrid"
uuid = "69a0a054-a29c-4d77-8818-cd7ec12cfcdc"
version = "1.0.0"
authors = ["Abdelrahman F. Abdelrahman"]

[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
FerriteGmsh = "4f95f4f8-b27c-4ae5-9a39-ea55e634e36b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
AlgebraicMultigrid = "1.1.0"
CommonSolve = "0.2.4"
Ferrite = "1"
FerriteGmsh = "1.2.1"
IterativeSolvers = "0.9"
LinearAlgebra = "1"
LinearSolve = "3.17.0"
Reexport = "1"
Tensors = "1"
TimerOutputs = "0.5"
julia = "1.10"

[extras]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = ["Test", "Tensors", "TimerOutputs", "Downloads", "IterativeSolvers"]
